#!/usr/bin/bash

# This script generates the HTML in index.html from any post that exists in the folder posts
# Requies the markdown program to run. Run `sudo pacman -S markdown` to install it.

# Clear the index.html file and load the head of the file
cat head > index.html 

# Loop over each markdown file in the posts directory.
# A post is assumed to start with a date e.g. 2014-08-16
for post in $(find posts/ -name "*.md")
do
    # Write the wraping div to the HTML file.
    echo "<div class=\"well text-left \">" >> index.html
    # Parse the markdown to HTML and append it to HTML file 
    markdown $post >> index.html
    # Generate a timestamp from the file name and append it to the document.
    echo "<div class=\" text-center \"> <p class=\" post-date \">" >> index.html
    echo "$post" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}' >> index.html
    echo "</p> </div>" >> index.html
    # Close the wrapping div.
    echo "</div>" >> index.html
done

# Append the tail of the document so that we have comple the HTML
cat tail >> index.html

# Dump the file so that we can se what is generated.
cat index.html
