#!/usr/bin/bash

# This script generates the HTML in index.html from any post that exists in the folder posts
# If you have never run this before, run scripts/install first.

#################################################
### F U N C T I O N   D E C L A R A T I O N S ###
#################################################

generatePost() {
    postSource=$1
    # Generate the post name from the source markdown file
    htmlPostFileName=$(echo "$postSource" | sed -e 's|released/|posts/|' -e 's|.md|/index\.html|')

    # Get folder name from file name by removing /index.html
    htmlPostFolderName=${htmlPostFileName::-10}

    # Create folder
    mkdir "$htmlPostFolderName"

    # Generate the post content and save it in the destination HTML file
    markdown "$postSource" > "$htmlPostFileName"

    postPattern="--content--"
    # Apply the template to the content
    cat "templates/post.html" | sed "/$postPattern/ r $htmlPostFileName" | sed "/$postPattern/ d" > tmp
    mv tmp "$htmlPostFileName"

    # Insert post label from file name
    # First remove the date part, then remove the file extension, lastly replace hyphens with spaces
    postHeader=$(echo "$htmlPostFileName" | cut -d'_' -f2 | cut -d'.' -f1 | tr '-' ' ')
    cat "$htmlPostFileName" | sed "s|--postheader--|$postHeader|i" > tmp
    mv tmp "$htmlPostFileName"

    # Add word count metadata
    metadata="Words: "$(wc -w "$postSource" | cut -d' ' -f1)
    
    # Insert the metadata into the HTML file placeholder
    cat "$htmlPostFileName" | sed "s/--metadata--/$metadata/i" > tmp
    mv tmp "$htmlPostFileName"

    # Extract the date from the file name
    postDate=$(echo "$postSource" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')
    # Insert the date into the HTML file placeholder
    cat "$htmlPostFileName" | sed "s/--date--/$postDate/i" > tmp
    mv tmp "$htmlPostFileName"

    # Generate the nav bar
    generateNavBar "post" "navbar"
    # Prepend navbar
    cat navbar "$htmlPostFileName" > tmp
    # Remove the left over file
    rm navbar
    mv tmp "$htmlPostFileName"

    echo "$htmlPostFileName"
}

generatePostPreview() {
    postSource=$1
    targetFile=$2

    previewFileName="preview"

    # Generate the post content and save it in a temporary file
    head "$postSource" | markdown > "$previewFileName"

    postPattern="--content--"
    # Apply the template to the content
    cat "templates/preview.html" | sed "/$postPattern/ r $previewFileName" | sed "/$postPattern/ d" > tmp
    mv tmp "$previewFileName"

    # Insert post label from file name
    # First remove the date part, then remove the file extension, lastly replace hyphens with spaces
    postHeader=$(echo "$postSource" | cut -d'_' -f2 | cut -d'.' -f1 | tr '-' ' ')
    cat "$previewFileName" | sed "s/--header--/$postHeader/i" > tmp
    mv tmp "$previewFileName"


    # Generate the post name from the source markdown file
    htmlPostFileName=$(echo $postSource | sed -e 's|released/|posts/|' -e 's|\.md|/|')

    # Add href to link in header and in continue button
    cat "$previewFileName" | sed "s|--href--|/$htmlPostFileName|g" > tmp
    mv tmp "$previewFileName"

    # Add word count metadata
    metadata="Words: "$(wc -w "$postSource" | cut -d' ' -f1)
    # Insert the metadata into the HTML file placeholder
    cat "$previewFileName" | sed "s/--metadata--/$metadata/i" > tmp
    mv tmp "$previewFileName"

    # Extract the date from the file name
    postDate=$(echo "$postSource" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')
    # Insert the date into the HTML file placeholder
    cat "$previewFileName" | sed "s/--date--/$postDate/i" > tmp
    mv tmp "$previewFileName"

    # Append newly created preview to index.html document
    cat "$previewFileName" >> "$targetFile"

    # Remove temp file
    rm "$previewFileName"
}


generateNavBar() {
    # Target of the generate
    target=$1
    # Declare target file variable
    targetFile=""
    if [[ "$target" = "about" ]]; then
        # Write to the about index file
        targetFile="about/index.html"
        # Set the about pill as active
        cat "templates/navbar_default.html" | sed "s/--homeactive--//g" | sed "s/--archiveactive--//g" | sed "s/--aboutactive--/active/g" > tmp
    elif [[ "$target" = "home" ]]; then
        # Write to the main index file
        targetFile="index.html"
        # Set home pill as active
        cat "templates/navbar_default.html" | sed "s/--homeactive--/active/g" | sed "s/--archiveactive--//g" | sed "s/--aboutactive--//g" > tmp
    elif [[ "$target" = "post" ]]; then
        # Read the target file from input
        targetFile=$2
        # Set all pills as inactive
        cat "templates/navbar_default.html" | sed "s/--homeactive--//g" | sed "s/--archiveactive--//g" | sed "s/--aboutactive--//g" > tmp
    elif [[ "$target" = "archive" ]]; then
        # Write to the archive page
        targetFile="archive/index.html"
        # Set archive pill as active
        cat "templates/navbar_default.html" | sed "s/--homeactive--//g" | sed "s/--archiveactive--/active/g" | sed "s/--aboutactive--//g" > tmp
    else
        echo "Unknown argument $target"
        exit 1
    fi
    # Add navigation to target file
    cat tmp >> "$targetFile"
    # Remove temp file
    rm tmp
}

# Remove all previously compiled posts and previews
rm -rf posts/* previews/*

# Clear the index.html file and load the head of the file
cat "templates/page_head.html" > index.html
generateNavBar "home"

# Loop over each markdown file in the post_src directory.
# A post is assumed to start with a date e.g. 2014-08-16
postCount=1;
maxNumberOfPreviews=10;
for postSource in $(find "released/" -name "*.md" | sort -n -r)
do
    if [[ $postCount -le $maxNumberOfPreviews ]]; then
        generatePostPreview "$postSource" "index.html"
    fi

    #Generate the entire post
    htmlPostFileName=$(generatePost "$postSource")

    # Make the HTML file containing the post a real HTML document
    cat "templates/page_head.html" \
        "$htmlPostFileName" \
        "templates/page_tail.html" > tmp
    mv tmp "$htmlPostFileName"

    # Increment post count
    postCount=$(($postCount+1))
done

# Append the tail of the document so that we have comple the HTML
cat "templates/page_tail.html" >> index.html

# Generate about page
aboutFile="about/index.html"
cat "templates/page_head.html" > "$aboutFile"
generateNavBar "about"
markdown "about/index.md" >> "$aboutFile"
cat "templates/page_tail.html" >> "$aboutFile"



# Generate the archive page
archiveFile="archive/index.html"
cat "templates/page_head.html" > "$archiveFile"
generateNavBar "archive"
# Create content file
touch archiveContent
# Loop over each markdown file in the post_src directory.
# A post is assumed to start with a date e.g. 2014-08-16
for postSource in $(find "released/" -name "*.md" | sort -n -r)
do
    cp "templates/archive_entry.html" archiveEntry

    # Extract the date from the file name
    date=$(echo "$postSource" | grep -o '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}')
    # Insert the date into the HTML file placeholder
    cat archiveEntry | sed "s/--archive-date--/$date/i" > tmp
    mv tmp archiveEntry

    # Extract name from file name
    title=$(echo "$postSource" | cut -d'_' -f2 | cut -d'.' -f1 | tr '-' ' ')
    # Insert it into template
    cat archiveEntry | sed "s/--archive-title--/$title/i" > tmp
    mv tmp archiveEntry

    # Create url
    postUrl=$(echo $postSource | sed -e 's/released\//posts\//' -e 's/\.md/\.html/')
    # Replace placeholder with url
    cat archiveEntry |  sed "s|--archive-href--|/$postUrl|i" > tmp
    mv tmp archiveEntry

    # Add mock topics
    topics=$(head -n 1 "$postSource" | cut -c 5- | rev | cut -c 4- | rev)
    # Replace placeholder with url
    cat archiveEntry |  sed "s/--archive-topics--/$topics/i" > tmp
    mv tmp archiveEntry

    # Generate word count
    words=$(wc -w "$postSource" | cut -d' ' -f1)
    # Add to template
    cat archiveEntry | sed "s/--archive-words--/$words/i" > tmp
    mv tmp archiveEntry

    cat archiveEntry >> archiveContent

done

rm archiveEntry

archivePattern="--archive-content--"
# Apply the template to the content
cat "templates/archive.html" | sed "/$archivePattern/ r archiveContent" | sed "/$archivePattern/ d" >> "$archiveFile"
rm archiveContent
cat "templates/page_tail.html" >> "$archiveFile"
