#!/usr/bin/bash

# This scripts helps with adding a new post, since the created files have some restrictions

# Verify that all parameters are provided
if [ "$#" != "1" ]
then
    echo "You have to supply a post tile!"
    exit 1
fi

# Map input to named variables
postTitle=$1

# Create file
postPath="new/"$(date -I)"_"$(echo "$postTitle" | tr ' ' '-')".md"
touch "$postPath"

# Open it in vim
atom "$postPath"
