#!/usr/bin/bash

# This scripts makes publishing changes simpler as publishing something is very repetitive.

if [ "$#" != "1" ]
then
    echo "You have to supply a commit message!"
    exit 1
fi

# We assign parameters to named variables.
CommitMessage=$1

# Generate the content
./scripts/generate > /dev/null

# Add all changes to git
git add --all

# Commit them with the supplied message
git commit -m "$CommitMessage"

# Push the changes
git push
