#!/usr/bin/node

// I was not impressed to sed with regard to replacing a pattern with all the contents of an HTML file
// so I hacked something together in node.

// This script provides a simple search and replace funtionality that does 
// not get affected by special characters and new lines.

var args = process.argv.slice(2);

if (args.length !== 3) {
    throw "Invalid number of args! Usage: node <source> <pattern> <replacement>";
}
var source = args[0];
var pattern = args[1];
var replacement = args[2];

var regex = new RegExp(pattern);
var result = source.replace(pattern, replacement);

console.log(result);
